#!/usr/bin/env python3
"""Generate src/data/network-map.ts from Natural Earth 1:50m countries.

Natural Earth is public domain. Download once, then run:

  curl -sL -o /tmp/ne50.geojson \
    https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson
  python3 scripts/build-network-map.py /tmp/ne50.geojson

The output is static SVG path data, so the site needs no mapping library.
"""
import json, math, sys
from pathlib import Path

LON_MIN, LON_MAX, LAT_MIN, LAT_MAX = -118.0, -33.0, -56.5, 33.0
SCALE = 10.0            # SVG units per degree
TOLERANCE = 0.07        # Douglas-Peucker tolerance in degrees
MIN_AREA = 0.02         # drop islands smaller than this (square degrees)

def project(lon, lat):
    return ((lon - LON_MIN) * SCALE, (LAT_MAX - lat) * SCALE)

def dp(points, tol):
    if len(points) < 3:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-12
    best, idx = 0.0, 0
    for i in range(1, len(points) - 1):
        x0, y0 = points[i]
        d = abs(dy * x0 - dx * y0 + x2 * y1 - y2 * x1) / norm
        if d > best:
            best, idx = d, i
    if best > tol:
        return dp(points[: idx + 1], tol)[:-1] + dp(points[idx:], tol)
    return [points[0], points[-1]]

def area(ring):
    return abs(sum(x0 * y1 - x1 * y0 for (x0, y0), (x1, y1) in zip(ring, ring[1:]))) / 2

def ring_path(ring):
    # A closed ring has identical endpoints, so simplify it as two halves.
    mid = len(ring) // 2
    simplified = dp(ring[: mid + 1], TOLERANCE)[:-1] + dp(ring[mid:], TOLERANCE)
    if len(simplified) < 4:
        return ''
    pts = [project(lon, lat) for lon, lat in simplified]
    out, last = [], None
    for x, y in pts:
        p = (round(x, 1), round(y, 1))
        if p != last:
            out.append(f'{p[0]:g},{p[1]:g}')
            last = p
    return 'M' + 'L'.join(out) + 'Z'

def inside(ring):
    lons = [p[0] for p in ring]
    lats = [p[1] for p in ring]
    cx, cy = sum(lons) / len(lons), sum(lats) / len(lats)
    return LON_MIN < cx < LON_MAX and LAT_MIN < cy < LAT_MAX

def main(src):
    data = json.loads(Path(src).read_text())
    countries = []
    for f in data['features']:
        props, geom = f['properties'], f['geometry']
        polys = geom['coordinates'] if geom['type'] == 'MultiPolygon' else [geom['coordinates']]
        parts = []
        for poly in polys:
            outer = poly[0]
            if not inside(outer) or area(outer) < MIN_AREA:
                continue
            d = ring_path(outer)
            if d:
                parts.append(d)
        if parts and props['ADM0_A3'] not in ('USA', 'SGS'):
            iso = props['ADM0_A3']
            countries.append((iso, props['NAME_EN'], ''.join(parts)))
    countries.sort()
    width = round((LON_MAX - LON_MIN) * SCALE)
    height = round((LAT_MAX - LAT_MIN) * SCALE)
    lines = [
        '// Generated by scripts/build-network-map.py from Natural Earth 1:50m',
        '// admin-0 countries (public domain). Do not edit by hand.',
        '',
        f'export const MAP_BOUNDS = {{ lonMin: {LON_MIN}, lonMax: {LON_MAX}, latMin: {LAT_MIN}, latMax: {LAT_MAX}, scale: {SCALE} }} as const;',
        f'export const MAP_VIEWBOX = {{ width: {width}, height: {height} }} as const;',
        '',
        'export const MAP_COUNTRIES: ReadonlyArray<{ iso: string; name: string; d: string }> = [',
    ]
    for iso, name, d in countries:
        lines.append(f'  {{ iso: {json.dumps(iso)}, name: {json.dumps(name)}, d: {json.dumps(d)} }},')
    lines += [
        '];',
        '',
        '/** Project longitude/latitude into the map viewBox. */',
        'export function projectLonLat(lon: number, lat: number): { x: number; y: number } {',
        '  return {',
        '    x: Math.round((lon - MAP_BOUNDS.lonMin) * MAP_BOUNDS.scale * 10) / 10,',
        '    y: Math.round((MAP_BOUNDS.latMax - lat) * MAP_BOUNDS.scale * 10) / 10,',
        '  };',
        '}',
        '',
    ]
    out = Path(__file__).resolve().parent.parent / 'src/data/network-map.ts'
    out.write_text('\n'.join(lines))
    print(f'{len(countries)} countries, {out.stat().st_size} bytes -> {out}')

if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else '/tmp/ne50.geojson')
